services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - config.env
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - config.env
    ports:
      - '5432:5432'
